name: flutter_mqchat
description: Using MQTT as chat protocol
version: 0.1.0
homepage: https://github.com/WahidNasri/flutter-mqtt-chat-client

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #==== MQTT CLIENT ====
  mqtt_client: ^9.6.5

  #==== UUID ====
  uuid: ^3.0.4

  #==== RXDART ====
  rxdart:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.1
  copy_with_extension_gen: ^2.0.2
  build_runner: ^2.0.4
flutter: